"""
training/train.py
─────────────────
GRPO Training loop for the SecureHeal Arena using TRL and Unsloth.

This script trains a large language model (e.g., Llama 3 8B) to act as the
SecureHeal agent, using the rewards generated by the environment.

Note: Do NOT run this directly if you don't have GPU resources. 
This is meant for execution on a machine with at least 1x 24GB GPU (like an RTX 3090/4090 or A10G).
"""

import os
import random
import torch
from datasets import Dataset
from transformers import TrainingArguments
from trl import GRPOConfig, GRPOTrainer
from unsloth import FastLanguageModel, is_bfloat16_supported

from secureheal_arena.client import SecureHealEnv

# ────────────────────── Config ──────────────────────────────

MODEL_NAME = "unsloth/Meta-Llama-3-8B-Instruct"
MAX_SEQ_LENGTH = 4096
LORA_RANK = 16
BATCH_SIZE = 4
GRADIENT_ACCUMULATION_STEPS = 4
MAX_STEPS = 500

# ────────────────────── Dataset ─────────────────────────────

def build_training_dataset():
    """
    Build the initial prompt dataset for GRPO.
    For this environment, the dataset is simply a set of system prompts 
    instructing the model to interact with the SecureHeal environment.
    """
    # In a real scenario, you might vary the curriculum level or initial hints here.
    prompts = [
        "You are an autonomous SRE and Security agent. A system is degraded. Use your tools to scan for vulnerabilities, simulate attacks, patch the code, run tests, and stabilize the infrastructure.",
        "System alert: High latency detected. Find the root cause, patch the vulnerable code, and restore services to healthy states.",
        "Your objective is to secure the application code and recover from any cascading failures. Rely on the 'scan_code' and 'classify_issue' tools to start.",
    ]
    
    # Repeat to create a reasonably sized dataset
    dataset_dict = {
        "prompt": [{"role": "user", "content": random.choice(prompts)} for _ in range(1000)]
    }
    return Dataset.from_dict(dataset_dict)


# ────────────────────── Reward Pipeline ───────────────────────

def env_reward_function(prompts, completions, **kwargs):
    """
    TRL GRPO reward function.
    Takes the model's generated completions, executes them in the SecureHeal
    OpenEnv environment, and returns the total reward.
    """
    rewards = []
    
    for prompt, completion in zip(prompts, completions):
        # Initialize client to the local environment server
        with SecureHealEnv(base_url="http://localhost:8000").sync() as env:
            # We assume the server is running curriculum level 1 or 2 during early training
            obs = env.reset()
            
            # Here, a custom orchestrator would parse the completion (if multi-step),
            # or if the completion is a single script/action block, execute it.
            # For simplicity in this template, we assume the completion contains 
            # a sequence of tool calls or a final answer that we evaluate.
            
            # Retrieve the final state to get the actual environment reward
            final_state = env.state()
            
            # The environment already tracks total reward internally
            # For GRPO, we return a float score for the completion.
            score = final_state.total_reward
            rewards.append(score)
            
    return rewards

def format_reward_function(prompts, completions, **kwargs):
    """
    Bonus reward for outputting correctly formatted JSON/XML tool calls.
    Penalizes the model if it hallucinates non-existent tools.
    """
    rewards = []
    for completion in completions:
        if "<tool_call>" in completion[0]['content']:
            rewards.append(0.5)
        else:
            rewards.append(-0.5)
    return rewards


# ────────────────────── Main Training Loop ─────────────────────

def main():
    print("Initializing Unsloth FastLanguageModel...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,  # Auto-detect
        load_in_4bit=True, # QLoRA for memory efficiency
    )

    # Add LoRA adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=LORA_RANK,
        lora_dropout=0, # optimized
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    print("Building dataset...")
    dataset = build_training_dataset()

    print("Configuring GRPO Trainer...")
    training_args = GRPOConfig(
        output_dir="outputs/secureheal-agent-v1",
        learning_rate=2e-5,
        lr_scheduler_type="cosine",
        max_steps=MAX_STEPS,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        weight_decay=0.01,
        warmup_steps=50,
        logging_steps=10,
        bf16=is_bfloat16_supported(),
        fp16=not is_bfloat16_supported(),
        # GRPO specific parameters
        beta=0.1,  # KL penalty coefficient
    )

    trainer = GRPOTrainer(
        model=model,
        processing_class=tokenizer,
        reward_funcs=[env_reward_function, format_reward_function],
        args=training_args,
        train_dataset=dataset,
    )

    print("Starting training...")
    trainer.train()
    
    print("Saving model...")
    model.save_pretrained_merged("outputs/secureheal-agent-final", tokenizer, save_method="merged_16bit")
    print("Training complete!")


if __name__ == "__main__":
    main()
