"""
training/train.py
─────────────────
GRPO Training loop for the SecureHeal Arena using TRL and Unsloth.

This script trains a large language model (e.g., Llama 3 8B) to act as the
SecureHeal agent, using the rewards generated by the environment.

Note: Do NOT run this directly if you don't have GPU resources. 
This is meant for execution on a machine with at least 1x 24GB GPU (like an RTX 3090/4090 or A10G).
"""

import os
import sys

# Disable torch.compile (Inductor allocates huge temp buffers that OOM on 8GB GPUs)
os.environ["TORCH_COMPILE_DISABLE"] = "1"
os.environ["TORCHDYNAMO_DISABLE"] = "1"

# Add parent directory to sys.path to import secureheal_arena
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from unsloth import FastLanguageModel, is_bfloat16_supported
import random
import torch
from datasets import Dataset
from transformers import TrainingArguments
from trl import GRPOConfig, GRPOTrainer

# Note: SecureHealEnv import removed — using offline heuristic rewards for training.
# To use live env rewards, start the server and re-enable env_reward_function.

# ────────────────────── Config ──────────────────────────────

MODEL_NAME = "unsloth/llama-3-8b-Instruct-bnb-4bit"
MAX_SEQ_LENGTH = 1024          # Reduced from 4096 to fit in 8GB VRAM
LORA_RANK = 8                   # Reduced from 16 to save memory
BATCH_SIZE = 1                  # Reduced from 4 — minimum for 8GB GPU
GRADIENT_ACCUMULATION_STEPS = 16  # Increased to keep effective batch = 16
MAX_STEPS = 500
NUM_GENERATIONS = 2             # GRPO generations per prompt (default can be 4-8)
MAX_COMPLETION_LENGTH = 128     # Max tokens generated per completion

# ────────────────────── Dataset ─────────────────────────────

def build_training_dataset():
    """
    Build the initial prompt dataset for GRPO.
    For this environment, the dataset is simply a set of system prompts 
    instructing the model to interact with the SecureHeal environment.
    """
    # In a real scenario, you might vary the curriculum level or initial hints here.
    prompts = [
        "You are an autonomous SRE and Security agent. A system is degraded. Use your tools to scan for vulnerabilities, simulate attacks, patch the code, run tests, and stabilize the infrastructure.",
        "System alert: High latency detected. Find the root cause, patch the vulnerable code, and restore services to healthy states.",
        "Your objective is to secure the application code and recover from any cascading failures. Rely on the 'scan_code' and 'classify_issue' tools to start.",
    ]
    
    # Repeat to create a reasonably sized dataset
    dataset_dict = {
        "prompt": [[{"role": "user", "content": random.choice(prompts)}] for _ in range(1000)]
    }
    return Dataset.from_dict(dataset_dict)


# ────────────────────── Reward Pipeline ───────────────────────
# Offline heuristic rewards — no SecureHeal server needed.
# These evaluate the model's completions based on content quality.

# Valid tool names from the SecureHeal environment
VALID_TOOLS = {
    "scan_code", "simulate_attack", "apply_patch", "run_tests",
    "restart_service", "clean_data", "reallocate_resources", "classify_issue",
}

def tool_usage_reward(prompts, completions, **kwargs):
    """
    R1: Rewards the model for mentioning valid SecureHeal tool names.
    Higher reward for using more distinct tools (encourages multi-step plans).
    """
    rewards = []
    for completion in completions:
        text = completion[0]["content"].lower()
        tools_used = sum(1 for tool in VALID_TOOLS if tool in text)
        # Scale: 0 tools = -0.5, 1 tool = 0.0, 4+ tools = 1.0
        score = min((tools_used - 1) / 3.0, 1.0) if tools_used > 0 else -0.5
        rewards.append(score)
    return rewards

def format_reward_function(prompts, completions, **kwargs):
    """
    R2: Rewards structured output (XML tool calls, JSON, or numbered steps).
    Penalizes unstructured prose-only responses.
    """
    rewards = []
    for completion in completions:
        text = completion[0]["content"]
        score = 0.0
        if "<tool_call>" in text or "</tool_call>" in text:
            score += 0.5
        if "{" in text and "}" in text:  # JSON-like structure
            score += 0.2
        if any(f"{i}." in text or f"Step {i}" in text for i in range(1, 6)):
            score += 0.3  # Numbered steps = structured plan
        if score == 0.0:
            score = -0.3  # Penalize pure prose
        rewards.append(min(score, 1.0))
    return rewards

def reasoning_reward(prompts, completions, **kwargs):
    """
    R3: Rewards multi-step reasoning and security-relevant analysis.
    Checks for diagnostic keywords that indicate the model is actually
    reasoning about vulnerabilities and system recovery.
    """
    REASONING_KEYWORDS = [
        "vulnerability", "exploit", "patch", "injection", "xss",
        "latency", "memory", "cpu", "restart", "failure",
        "root cause", "diagnosis", "fix", "remediat", "mitigat",
        "test", "verify", "monitor", "stable", "recover",
    ]
    rewards = []
    for completion in completions:
        text = completion[0]["content"].lower()
        hits = sum(1 for kw in REASONING_KEYWORDS if kw in text)
        # Scale: 0 hits = -0.3, 3 hits = 0.3, 6+ hits = 1.0
        score = min((hits - 1) / 5.0, 1.0) if hits > 0 else -0.3
        rewards.append(score)
    return rewards

def quality_reward(prompts, completions, **kwargs):
    """
    R4: Rewards completions of reasonable length. Penalizes very short
    (lazy) or excessively long (rambling) outputs.
    """
    rewards = []
    for completion in completions:
        text = completion[0]["content"]
        word_count = len(text.split())
        if word_count < 15:
            score = -0.5   # Too short / empty
        elif word_count < 30:
            score = 0.0    # Marginal
        elif word_count <= 150:
            score = 0.5    # Good length
        else:
            score = 0.2    # Verbose but not terrible
        rewards.append(score)
    return rewards


# ────────────────────── Main Training Loop ─────────────────────

def main():
    print("Initializing Unsloth FastLanguageModel...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,  # Auto-detect
        load_in_4bit=True, # QLoRA for memory efficiency
    )

    # Add LoRA adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        lora_alpha=LORA_RANK,
        lora_dropout=0, # optimized
        bias="none",
        use_gradient_checkpointing="unsloth",
    )

    print("Building dataset...")
    dataset = build_training_dataset()

    print("Configuring GRPO Trainer...")
    training_args = GRPOConfig(
        output_dir="outputs/secureheal-agent-v1",
        learning_rate=2e-5,
        lr_scheduler_type="cosine",
        max_steps=MAX_STEPS,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        weight_decay=0.01,
        warmup_steps=50,
        logging_steps=10,
        bf16=is_bfloat16_supported(),
        fp16=not is_bfloat16_supported(),
        # GRPO specific parameters
        beta=0.1,                                   # KL penalty coefficient
        num_generations=NUM_GENERATIONS,             # Fewer generations = less VRAM
        max_completion_length=MAX_COMPLETION_LENGTH,  # Shorter completions = less VRAM
        torch_compile=False,                         # Disable compile to avoid huge temp buffers
    )

    trainer = GRPOTrainer(
        model=model,
        processing_class=tokenizer,
        reward_funcs=[tool_usage_reward, format_reward_function, reasoning_reward, quality_reward],
        args=training_args,
        train_dataset=dataset,
    )

    print("Starting training...")
    trainer.train()
    
    print("Saving model...")
    model.save_pretrained_merged("outputs/secureheal-agent-final", tokenizer, save_method="merged_16bit")
    print("Training complete!")


if __name__ == "__main__":
    main()
